### ISSUE TITLE
Stackクラスにある文字列連結機能をBufferクラスに分離する

### ISSUE THREAD

**Issue by shiracamus** [massongit/rpn-calculator#2]
単一責任の原則に乗っ取り、Stackは push, pop に専念し、文字列の連結やクリア機能はBufferクラスに分けましょう。

**Comment by massongit** [comment]
StackにBufferをもたせ、Bufferに溜めていくといった形を想像していますが、それで合っていますでしょうか？ (Calculatorに持たせると、Calculatorにもpushメソッドができ、なんとなく気持ち悪いので)

**Comment by shiracamus** [comment]
いえ、新たにBufferクラス(StringBufferとか名前は何でもいいです) を作って欲しいです。
Stackは本来の仕事であるpush/popだけに専念させましょう

**Comment by massongit** [comment]
どちらの意味合いでおっしゃっているのでしょうか？
* RPNCalculatorにBufferクラスをもたせる
* main関数上でBufferクラスのインスタンスを生成する

**Comment by shiracamus** [comment]
Calculatorクラスのpush, popメソッドが気持ち悪いのであれば、confirmValue と getValue といったメソッド名に変えてはいかがでしょう？

**Comment by massongit** [comment]
すなわち、『RPNCalculatorクラスにBufferクラスのインスタンスをもたせる』ということですね？ (メソッド名に関してはおいおい考えますが)

**Comment by shiracamus** [comment]
はい。Calculatorがバッファを持ちます。
ハードウェア部品で電卓を作ることを考えてみると、値をスタックする部品と、文字列を溜め込むバッファ部品は独立に存在していて、それが電卓内部で配線されるはずです。
バッファにある値をスタックにpushするのは電卓本体の仕事ですよね。

**Comment by massongit** [comment]
『クラスを分けた方が良い』とアドバイスするのであれば、『分けたクラスのインスタンスをどこで持たせた方が良いか』がないと情報としては不完全ですので、そのあたりを最初から明記するように心がけると良いアドバイスになるかと思います。

**Comment by shiracamus** [comment]
単一責任の原則に従ってStackはpush, popに専念しましょう と書いたので、Stackに持たせないことが伝わるかと思ったのですが、言葉が足りませんでしたね。
main関数はUI担当で、ユーザからの入力を電卓のキー操作に橋渡しすることに専念。
単一責任の法則については、ネット検索すれば以下のような記事がいろいろ見つかると思います。
http://プログラマが知るべき97のこと.com/%E3%82%A8%E3%83%83%E3%82%BB%E3%82%A4/%E5%8D%98%E4%B8%80%E8%B2%AC%E4%BB%BB%E5%8E%9F%E5%89%87
http://qiita.com/gomi_ningen/items/02c42e2487d035f9c3c8

**Comment by shiracamus** [comment]
> Calculatorにもpushメソッドができ、なんとなく気持ち悪いので

スタックにpushするのは電卓の仕事なので、プライベートメソッドとしてpushメソッドがあるのは気持ち悪くないですよ。
スタックに文字列バッファ機能があるほうがよっぽど気持ち悪いです。
Stackではない別のクラス名にすればよかったのかもしれません。でもそのときはStackクラスのサブクラスにするのは無しです。リスコフの置換原則に反しますので。

**Comment by shiracamus** [comment]
Bufferを使った場合の例をqiitaにコメントしておきました。
http://qiita.com/SUZUKI_Masaya/items/6a19ecfb2eae66ec0fb4#comment-86897dbbc21e6b57d384
